version = 3.9.4
project.git = true
  
runner.dialect = scala3
  
maxColumn = 120
trailingCommas = always
  
continuationIndent {
  callSite = 2
  defnSite = 2
}

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  prefercurlyfors
]

align {
  preset = most
  multiline = true
  openParenDefnSite = false
  openParenCallSite = false

  tokenCategory {
    Equals = Assign
    LeftArrow = Assign
  }

  tokens."+" = [
    { code = "%", owner = "Term.ApplyInfix" }
    { code = "%%", owner = "Term.ApplyInfix" }
    { code = "%%%", owner = "Term.ApplyInfix" }
    { code = "=>", owner = "(Case|Term.Function)" }
    { code = "<-", owner = "Enumerator.Generator" }
    { code = "=", owner = "(Defn.Val|Defn.Var|Type|Enumerator.Val|Assign|Term.Param)" }
    { code = "->", owner = "Term.ApplyInfix" }
    { code = "returns", owner = "Term.ApplyInfix" }
    { code = "was", owner = "Term.ApplyInfix" }
    { code = "shouldBe", owner = "Term.ApplyInfix" }
  ]
}

rewrite.redundantBraces.parensForOneLineApply = false
